mission = """
Sidekick is a human-in-the-loop system designed to support software developers
through GenAI automation. Sidekick should be easy for developers to set up and
use, intuitive to understand and highly introspectable with realtime feedback
and granular tracking. It should be able to be guided by developers using it,
but do as much as can be done reliably without the human in the loop, before
engaging them. The core mission of Sidekick is to make developers more
productive as they work within large existing code bases.
"""

[edit_code]
hints = """
Refer to *.side.md files that describe how that area of the codebase should work.
Always read files with that naming scheme that are located in an area that is
relevant to the functionality you are working on. Only edit such files with express
directives to do so from the user, otherwise tell the user to make those edits
themselves, as they convey the user's intent which we do not want to inadvertently
corrupt.

Write or update unit tests for all major functionality. Feel free to make class
attributes internal instead of private to make it easier to write these unit tests.

Always handle errors, e.g. by showing an error message where appropriate. For error
handling, avoid exceptions in favor of Either or Result-like types. An example of
this is ApiResponse, a sealed class over Success and Error. That said, sometimes
exceptions may be necessary, eg when an error is unrecoverable. It can sometimes be
acceptable to use exceptions when the exception is meant to never happen in
practice, and indicates a program error, but do this sparingly.

### Testing

Most tests dealing with coroutines use UnconfinedTestDispatcher, so advanceUntilIdle
should not be used typically. Components that make use of coroutines, eg for IO, should allow a coroutine dispatcher to be passed in their constructors (defaulted to an appropriate value), and tests should pass in their testDispatcher.

Tests of components should always extend SidekickBaseTestCase, which is a subclass of a junit TestCase. So use junit assertions that are inherited from that. Don't use @Before but instead override setUp method. And don't use @Test but instead start test method names with the word "test".

To make child components testable, make them internal instead of private, so unit tests can access them.

There is some slight flakiness associated with failures with VFS and thus indexing files. The exceptions this results in include "Index data initialization failed" and "VFS can't be initialized", or similar VFS issues. If you see such errors, those are typically transient and no attempt should be made to fix these, just re-run the tests. However, if re-running the tests result in the same failures, ask the user for help.
"""

[[test_commands]]
command = "./gradlew test"